export interface Team {
  id: string;
  name: string;
  shortName: string;
  flag: string;
}

export const TEAMS: Team[] = [
  { id: 'fwc', name: 'FIFA World Cup', shortName: 'FWC', flag: '🏆' },
  { id: 'mexico', name: 'Mexico', shortName: 'MEX', flag: '🇲🇽' },
  { id: 'south-africa', name: 'South Africa', shortName: 'RSA', flag: '🇿🇦' },
  { id: 'korea-republic', name: 'Korea Republic', shortName: 'KOR', flag: '🇰🇷' },
  { id: 'czechia', name: 'Czechia', shortName: 'CZE', flag: '🇨🇿' },
  { id: 'canada', name: 'Canada', shortName: 'CAN', flag: '🇨🇦' },
  { id: 'bosnia-herzegovina', name: 'Bosnia-Herzegovina', shortName: 'BIH', flag: '🇧🇦' },
  { id: 'qatar', name: 'Qatar', shortName: 'QAT', flag: '🇶🇦' },
  { id: 'switzerland', name: 'Switzerland', shortName: 'SUI', flag: '🇨🇭' },
  { id: 'brazil', name: 'Brazil', shortName: 'BRA', flag: '🇧🇷' },
  { id: 'morocco', name: 'Morocco', shortName: 'MAR', flag: '🇲🇦' },
  { id: 'haiti', name: 'Haiti', shortName: 'HAI', flag: '🇭🇹' },
  { id: 'scotland', name: 'Scotland', shortName: 'SCO', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿' },
  { id: 'usa', name: 'USA', shortName: 'USA', flag: '🇺🇸' },
  { id: 'paraguay', name: 'Paraguay', shortName: 'PAR', flag: '🇵🇾' },
  { id: 'australia', name: 'Australia', shortName: 'AUS', flag: '🇦🇺' },
  { id: 'turkiye', name: 'Türkiye', shortName: 'TUR', flag: '🇹🇷' },
  { id: 'germany', name: 'Germany', shortName: 'GER', flag: '🇩🇪' },
  { id: 'curacao', name: 'Curaçao', shortName: 'CUW', flag: '🇨🇼' },
  { id: 'cote-divoire', name: 'Côte d\'Ivoire', shortName: 'CIV', flag: '🇨🇮' },
  { id: 'ecuador', name: 'Ecuador', shortName: 'ECU', flag: '🇪🇨' },
  { id: 'netherlands', name: 'Netherlands', shortName: 'NED', flag: '🇳🇱' },
  { id: 'japan', name: 'Japan', shortName: 'JPN', flag: '🇯🇵' },
  { id: 'sweden', name: 'Sweden', shortName: 'SWE', flag: '🇸🇪' },
  { id: 'tunisia', name: 'Tunisia', shortName: 'TUN', flag: '🇹🇳' },
  { id: 'belgium', name: 'Belgium', shortName: 'BEL', flag: '🇧🇪' },
  { id: 'egypt', name: 'Egypt', shortName: 'EGY', flag: '🇪🇬' },
  { id: 'ir-iran', name: 'IR Iran', shortName: 'IRN', flag: '🇮🇷' },
  { id: 'new-zealand', name: 'New Zealand', shortName: 'NZL', flag: '🇳🇿' },
  { id: 'spain', name: 'Spain', shortName: 'ESP', flag: '🇪🇸' },
  { id: 'cabo-verde', name: 'Cabo Verde', shortName: 'CPV', flag: '🇨🇻' },
  { id: 'saudi-arabia', name: 'Saudi Arabia', shortName: 'KSA', flag: '🇸🇦' },
  { id: 'uruguay', name: 'Uruguay', shortName: 'URU', flag: '🇺🇾' },
  { id: 'france', name: 'France', shortName: 'FRA', flag: '🇫🇷' },
  { id: 'senegal', name: 'Senegal', shortName: 'SEN', flag: '🇸🇳' },
  { id: 'iraq', name: 'Iraq', shortName: 'IRQ', flag: '🇮🇶' },
  { id: 'norway', name: 'Norway', shortName: 'NOR', flag: '🇳🇴' },
  { id: 'argentina', name: 'Argentina', shortName: 'ARG', flag: '🇦🇷' },
  { id: 'algeria', name: 'Algeria', shortName: 'ALG', flag: '🇩🇿' },
  { id: 'austria', name: 'Austria', shortName: 'AUT', flag: '🇦🇹' },
  { id: 'jordan', name: 'Jordan', shortName: 'JOR', flag: '🇯🇴' },
  { id: 'portugal', name: 'Portugal', shortName: 'POR', flag: '🇵🇹' },
  { id: 'congo-dr', name: 'Congo DR', shortName: 'COD', flag: '🇨🇩' },
  { id: 'uzbekistan', name: 'Uzbekistan', shortName: 'UZB', flag: '🇺🇿' },
  { id: 'colombia', name: 'Colombia', shortName: 'COL', flag: '🇨🇴' },
  { id: 'england', name: 'England', shortName: 'ENG', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  { id: 'croatia', name: 'Croatia', shortName: 'CRO', flag: '🇭🇷' },
  { id: 'ghana', name: 'Ghana', shortName: 'GHA', flag: '🇬🇭' },
  { id: 'panama', name: 'Panama', shortName: 'PAN', flag: '🇵🇦' },
];
